### ISSUE TITLE
BUG LIST

### ISSUE THREAD

**Issue by rgleason** [rgleason/weather_routing_pi#190]
This is a search on BUG
which results in a list of about 17 Bugs.

**Comment by Gilletarom** [comment]
I think these BUGs and other RFEs should be closed because they relate to too old versions of WR.

**Comment by rgleason** [comment]
Yes they are old, but how were they fixed?  We have no known Commit that fixes them.  
Do they still occur now?  I have not tested it.

**Comment by Gilletarom** [comment]
Durant l'été 2024, jusqu'à l'automne, j'ai utilisé WR et depuis ce temps la, même actuellement, ce problème a complètement disparu. Voila pourquoi je propose de ne pas garder cette déclaration de bug de le clore. On observe que plus personne n'en parle par ailleurs.

**Comment by rgleason** [comment]
I have had a number of reports about this problem in the area of the date change around Hawaii.  This needs to be confirmed to be a fact that it is fixed.  Someone needs to run the proper tests.

**Comment by sebastien-rosset** [comment]
If some of these issues still exist, can you create one GitHub issue per specific problem?

**Comment by rgleason** [comment]
Yes, I have no reason to believe they don't exist. I know of no programming or conmit for these specific bugs.

I can test for thesw when I get home, but there are dateline problems in the code.

Closing since these 3 issues are written up. Glad you have seen the issues.
