### ISSUE TITLE
Bug:  Api118 merged into Master : all OS failed

### ISSUE THREAD

**Issue by rgleason** [rgleason/weather_routing_pi#321]
See  https://github.com/rgleason/weather_routing_pi
Look at red X dropdown.
Review any of those builds.
CircleCI shows the reasons.
Use CTRL+F and search for "error" in the sections.

```
  Utilities.cpp
  LineBufferOverlay.cpp
C:\Users\circleci\project\src\RoutingTablePanel.cpp(634,27): error C3861: 'toUsrDateTimeFormat_Plugin': identifier not found [C:\Users\circleci\project\build\weather_routing_pi.vcxproj]
C:\Users\circleci\project\src\RoutingTablePanel.cpp(890,17): warning C4018: '<': signed/unsigned mismatch [C:\Users\circleci\project\build\weather_routing_pi.vcxproj]
  PolygonRegion.cpp
  WeatherRoutingUI.cpp
  icons.cpp
  zuFile.cpp
```

**Comment by sebastien-rosset** [comment]
I have fixed this with #323

**Comment by rgleason** [comment]
Still failing.  
https://github.com/rgleason/weather_routing_pi/issues/324#issuecomment-2841186663
See https://github.com/rgleason/weather_routing_pi/issues/324#issuecomment-2841614435

ater: Now I think that we have to comment out this feature and merge it without the ability to dim to night modes. Then when we move to api119 we can add it back.

**Comment by sebastien-rosset** [comment]
Is this issue fixed?
