### ISSUE TITLE
BUG: Grib plugin version not supported reported on clean OCPN 5.12.0-0 + latest WR 1.15.32.0

### ISSUE THREAD

**Issue by quinton-hoole** [rgleason/weather_routing_pi#457]
It's not clear which version of the grib plugin is shipped with OCPN 5.12.0-0 (it doesn't seem to be reported in the usual places), but the WR version that gets installed by default, says it doesn't like it.

But WR does appear to work with it.  Do we need to improve this, to make the latest WR work with the latest OCPN Grib plugin?

Windows 11
OCPN 5.12.0-0
Grib plugin (unknown version - shipped with  OCPN 5.12.0-0)

<img width="447" height="195" alt="Image" src="https://github.com/user-attachments/assets/adb72cab-959e-439d-8f36-03fc59939548" />
<img width="1207" height="555" alt="Image" src="https://github.com/user-attachments/assets/e5e9b59c-ccd4-4b76-9f87-22e58e1b9d48" />

**Comment by quinton-hoole** [comment]
> Yes, there is version checking I believe for grib and climatology. Yes

Yes, that is fairly obvious from my report. However, to be clear, the main points of this big report are:

1. The latest release of the weather routing plugin, reports that it is incompatible with the latest release of the grib plugin, which I believe comes bundled with the latest release of ocpn. This is confusing to users, and presumably not the intention. 
2. Moreover, given that ocpn and the weather routing plugin are updated independently, it is not feasible to have the weather routing plugin only compatible with 1 version of the grib plugin. It needs to be compatible with a range of grib plugin versions (perhaps all after a certain version, if they all provide a backward-compatible api). 
3. Even though an error related to the grib plugin version is displayed, the weather routing calculation, which is based upon the grib from the grib plugin, seems to succeed? So either the error should not be reported, or the calculation should not succeed, or the error should be clearly reworded as a warning, with an explanation of why the user is being warned.

**Comment by quinton-hoole** [comment]
> I will look at this tonight and try to make the necessary adjustment (shouldn't be hard) and build it for all OS.

Great! 👍 I'd be happy to review that change for you.

**Comment by rgleason** [comment]
@quinton-hoole   I think the versions should all be ok.  Please see. https://opencpn.zulipchat.com/#narrow/dm/399865,813668,881165-group/near/539446862

**Comment by quinton-hoole** [comment]
Rick Gleason [said]

Grib plugin version is listed here, but I think that is an old file
https://github.com/OpenCPN/OpenCPN/blob/master/plugins/grib_pi/src/version.h

#define PLUGIN_VERSION_MAJOR 1
#define PLUGIN_VERSION_MINOR 2
#define PLUGIN_VERSION_DATE ""
Grib_pi.h lists the version that I think is actually used:

#define PLUGIN_VERSION_MAJOR 5
#define PLUGIN_VERSION_MINOR 0

#define MY_API_VERSION_MAJOR 1
#define MY_API_VERSION_MINOR 16
Weather_routing_pi.cpp Line 42 start

// Define minimum and maximum versions of the grib plugin supported
#define GRIB_MAX_MAJOR 5
#define GRIB_MAX_MINOR 0
#define GRIB_MIN_MAJOR 4
#define GRIB_MIN_MINOR 1
So it is my conclusion that the WR_pi is good for the current version of Grib_pi!

// Define minimum and maximum versions of the climatology plugin supported

#define CLIMATOLOGY_MAX_MAJOR 1
#define CLIMATOLOGY_MAX_MINOR 6
#define CLIMATOLOGY_MIN_MAJOR 0
#define CLIMATOLOGY_MIN_MINOR 10
The current version of Climatology is 1.6.33 therefore WR_pi will read it.

Thanks. I'd suggest you add the above directly to https://github.com/rgleason/weather_routing_pi/issues/457 rather than link from a public bug report back to this private chat that deals with many other things. Also, I think that there are some followup items related to the bug, that I can add to the bug report once you've done this.

**Comment by sebastien-rosset** [comment]
One thing to keep in mind is that the grib plugin is part of the OpenCPN git repo. So typically knowing the opencpn version determines what code was used to build the grib plugin.

That is unless you do something special like reinstalling the grib plugin from a different release.

**Comment by rgleason** [comment]
I've cleaned up the first comment and reformatted it to be understood.
@quinton-hoole  if you agree, please close this.

**Comment by quinton-hoole** [comment]
> @quinton-hoole  what exactly are you doing? What version of OpenCPN, weather_routing and girb_pi?  
> The message should say **"Use Grib_pi versions 4.1 to 5.0'**  in accord with min and max.  That should be corrected.
> 
> However, I don't know enough about your install.

Hi Rick. I answered all of those questions in the original bug report above.

**Comment by rgleason** [comment]
Quite honestly I think this should be reported in OpenCPN Issues, because I don't think the problem is due to weather_routing!

Also the buggy popup  should be reported The message should say "Use Grib_pi versions 4.1 to 5.0' in accord with min and max. That should be corrected.

But I have not had this problem and thus cannot report it.

**Comment by rgleason** [comment]
Quinton, thank you for making the warning clearer and more explicit. I still don't understand why you get the warning if you were using the packaged Opencpn 5.12.0 version of grib pi? Please explain if you can.

Sebastien may I merge this now, hopefully you will pull it..?

**Comment by quinton-hoole** [comment]
I verified that I'm running Windows 11, OCPN 5.12.0 and WR_pi 1.15.32 (not 1.15.32).  The problem is reproducible on my system (from which I took the following screen shots today).

This was the result of installing distributed those from the standard places, a few weeks back.

I will have some more time later this week to look deeper if needed.

<img width="584" height="484" alt="Image" src="https://github.com/user-attachments/assets/d320b10b-6423-43b3-8215-04505bb74171" />
<img width="438" height="183" alt="Image" src="https://github.com/user-attachments/assets/c9152bf9-9d17-4df2-a692-477a8fa60439" />

**Comment by quinton-hoole** [comment]
Does the build number on your OpenCPN match mine?

<img width="119" height="25" alt="Image" src="https://github.com/user-attachments/assets/482f8802-ae8f-4a19-ba49-b89a4a54b867" />

I will complete all the steps as soon as I have time, but I doubt it will make much difference. 

Feel free to close this issue if it's just irritating you.  But I'm pretty sure I'm not the only one experiencing it.  All I did (what most users will do) is install the OpenCPN build directly from the downloads page (the one people would have found a few weeks ago if they googled for "OpenCPN downloads"). And I installed the WR plugin directly from the master catalogue. And my Windows 11 machine is brand new.  It has almost nothing other than OCPN + WR installed on it. There's nothing unusual about my setup at all.

**Comment by sebastien-rosset** [comment]
> I agree that we should not close this bug.
> 
> I think we should make the barrier to entry as low as possible for people to report bugs, so at least bugs are less likely to go unreported. If people have to fill in a mostly superfluous template, in the middle of the often critical workflow while sailing, they simply won't report the issue, and it will go unreported and unfixed, as many do.

For this issue, it's difficult to understand what problem(s) you are reporting, because you are not following the template. This creates back and forth. Let me explain by taking each of your sentences in the description:

> It's not clear which version of the grib plugin is shipped with OCPN 5.12.0-0 (it doesn't seem to be reported in the usual places)

Here is a suggestion to reformulate, though it's a bit unclear what you have in mind. You seem to state that OpenCPN should show the version of the GRIB plugin, but you don't say it very explicitly.

### Expected Behavior
The version of the grib plugin shipped with OCPN 5.12.0-0 should be clearly reported in plugin version information locations such as Options -> Plugins or the `opencpn-cmd list-plugins` CLI command.

### Actual Behavior
The version of the grib plugin shipped with OCPN 5.12.0-0 is not displayed in plugin version information locations such as Options -> Plugins or the `opencpn-cmd list-plugins` CLI command, making it unclear which version is included.

If that's what you have in mind, then it should be tracked as a separate issue, and it belongs to OpenCPN core, not the weather rouging plugin. The same goes with the next problems. The basic issue with your formulation is that it's hard to take action.

> but the WR version that gets installed by default, says it doesn't like it. - For Opencpn 5.12.0 Grib_pi 5.0 version.
> But WR does appear to work with it. Do we need to improve this to make the latest WR work with the latest OCPN Grib plugin?

Here is a suggested reformulation:

### Description
Weather Routing plugin displays an incompatibility warning for the grib plugin that ships with OCPN 5.12.0-0, even though the plugins appear to work together correctly.

### Steps to Reproduce

1. Install OpenCPN 5.12.0-0 on Windows 11 (includes bundled grib plugin)
2. Install Weather Routing plugin version 1.15.32 
3. See warning dialog

Do not forget to put the specific version of the WR plugin and the specific version of OpenCPN, including the git hash. Based on the entire thread, it looks like it is:

<img width="156" height="43" alt="Image" src="https://github.com/user-attachments/assets/ca61eab6-56a1-4849-863f-25d8ddf3a72b" />

I had to go through the entire thread to figure out which version of WR you are using, though I'm not entirely sure if that's the version you are having a problem with.

But it's way more efficient to identify the key points in the top-level Github description. It would be great if you can update the description such that we have an exact sequence of the steps to reproduce. Then we can move on to root causing the problem.

### Expected Behavior
No compatibility warning should be displayed when using Weather Routing with the grib plugin that ships with OCPN 5.12.0-0, since they work together correctly.

### Actual Behavior
A warning dialog appears stating **"Grib plugin version not supported. Use versions 4.1 to 4.1"** even though Weather Routing appears to function properly with the installed grib plugin.

> 
> Sometimes bugs are trivial for developers to reproduce, or it is trivial for a developer to respond that the bug has already been fixed in a later version, in which case forcing users to jump through unnecessary hoops like completing arduous templates, uploading log files, screen shots etc to report the presence of an apparent bug is ingenious. As I mentioned, it just reduces the chance that a bug will be reported and fixed.
> 
> Once, like is the case here, it proves non-trivial to reproduce a bug, then I think it's reasonable to request a more comprehensive report, as has been done here, and which I have agreed to do.
> 
> As for root causing, I have already made some attempt to do so, and so far failed, for the following reasons:
> 
> 1. Part of that is because I don't have a full understanding of how and when the plugins are built and uploaded to the plugin catalogue, and how trustworthy the version stamps on them are. I think that until we have a reliable build hash included somewhere in the plugin version, or log file, we can't for example be sure whether the version 1.15.32 that Rick is using is actually the same build that I am using, or perhaps a different build with the same version number. That's why I described exactly how I obtained my WR in plugin build. I'm also not clear on how commits are merged into the various branches of WR. You and I seem to merge into the api118 branch, but there is also an api120 branch, and a master branch. I see that the latest OpenCPN 5.12.0 exposes plugin API 120. Does that mean that the plugin manager in OpenCPN 5.12.0 automatically installs a version of the WR plugin that supports a plugin api v 120? Do we have such a build in the plugin catalogue? I don't know.
> 2. I don't have a good enough working relationship with git to be able to figure out the full history of every line of code, and exactly which lines of code are present in which build.
> 3. What is clear to me, based on the message I'm seeing "use version 4.1 to 4.1", is that there are only really one way I can imagine that that can be generated, given that I'm using standard production release builds:
>    the code that you wrote (if I'm reading the git history correctly) to check the version and and generate the error message was at some point in the past incorrect (either version_min and version_max were both defined to be 4.1, or the printf statement to generate the message was incorrect, using version_min in both cases), and has subsequently been fixed but that fix has not yet been included in the build, somehow.
> 
> I would very much appreciate it if you and Rick could figure out why the code that you wrote to check the versions, that until recently was in the api118 branch, is not the same code that is running in the plugin version that I am running, and which is (or was until recently, perhaps) in the master plugin catalogue.

I didn't write that code, but it's not very important who wrote the code, we just have to collectively root cause the problem. With git history, you could see I executed `clang-format -i` on all the code base to reformat the code. This means that almost everything has been touched by me. But the git history does show the the original code:

https://github.com/rgleason/weather_routing_pi/blame/2df8fd5a487adea2b2d6730f210003060ae4445d/src/weather_routing_pi.cpp

If I understand the problem correctly, you see the following popup:

**"Grib plugin version not supported. Use versions 4.1 to 4.1"**

Unfortunately you 



> 
> But if neither of you can reproduce the problem, then I guess I will have to root cause it. But I don't have time to do that now.

**Comment by quinton-hoole** [comment]
> Can you clarify if the version of the WR plugin was built locally from your workspace? Or was it downloaded from the internet? If so, which version?

Sorry, I thought I made this very clear, from the beginning, and repeatedly thereafter. I have never made a local build of either OpenCPN or the WR plugin on my windows machine, ever.  I don't even know how to yet. I just installed the OpenCPN software from the official downloads page. And I installed the WR plugin using the master plugin catalogue.

When I have time to dig deeper, I will. In the mean time, it would be useful to understand exactly which WR_pi commits are merged into which branches, and from which of these branches builds are created and incorporated into the master plugin catalogue.

**Comment by quinton-hoole** [comment]
I have seen that unhandled exception occasionally too, but usually after the "Grib plugin version not supported" warning has been displayed. 

I just uninstalled and re-installed the weather routing plugin from the master plugin catalogue, and was trivially able to reproduce the warning.  It's worth noting that the warning is only displayed once for any given run of OpenCPN.  This is due to the following lines of code, which ensure that it is only displayed once.

https://github.com/rgleason/weather_routing_pi/blob/5d45843e8a607aaaf6e74ee9bca5ddbe3613b550/src/weather_routing_pi.cpp#L259

So to reproduce the warning, you will have to restart OpenCPN. 

The main reason I'm bothering to chase this bug down is that I'm not sure that the weather routing plugin binary in the master plugin catalogue contains the source code that we think it does. 

As one last attempt I will install the latest version of OpenCPN core, from the official download site, and install the latest weather routing plugin from the master plugin catalogue and see whether I can reproduce the problem.

**Comment by quinton-hoole** [comment]
Yes, @rgleason I can confirm that I have reproduced the problem on OpenCPN 5.12.4

<img width="388" height="150" alt="Image" src="https://github.com/user-attachments/assets/82096fd5-2273-4900-83b4-220295ff13e8" />
<img width="444" height="194" alt="Image" src="https://github.com/user-attachments/assets/4bf46cc7-359e-4aeb-a22d-c4d415eaa304" />

**Comment by quinton-hoole** [comment]
Never mind.  I think I found the binary (by digging through the log file):

dir C:\Users\quint\AppData\Local\opencpn\plugins\weather_routing_pi.dll


    Directory: C:\Users\quint\AppData\Local\opencpn\plugins


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         6/22/2025   7:15 AM        2774016 weather_routing_pi.dll

So that is consistent with what's in github, as the tagged release:

https://github.com/rgleason/weather_routing_pi/releases/tag/v1.15.32.0

**Comment by quinton-hoole** [comment]
So at this point @rgleason (and @sebastien-rosset ) all I can suggest is that you follow my instructions in the original bug report to reproduce the warning. Given the apparent state of the source code used to build that binary, I'm at a loss to explain how the software is behaving the way it is, but it is.

**Comment by rgleason** [comment]
This is a bug in Opencpn 5.12.0 that was fixed by 5.12.2 and 5.12.4.  We should not be wasting time on this in my opinion, and should close it.

**Comment by quinton-hoole** [comment]
No, i don't believe it can be closed yet. I will verify that it's still reproducible. Until we understand what the problem is, I think we should leave it open.

**Comment by G0rocks** [comment]
I just encountered this issue also after updating all the plugins I have installed.
I opened an issue on the openCPN repo since the GRIB plugin version is not shown in the addon manager, see https://github.com/OpenCPN/OpenCPN/issues/5171.

Running OpenCPN 5.12.4-0 and weather routing 1.15.45.7 and I have no idea what the Grib plugin version is but presumably the latest version since I just updated all my plugins today.
